### ISSUE TITLE
Recaptcha as part of toolset

### ISSUE THREAD

**Issue by philwareham** [Bloke/zem_contact_reborn#17]
It would be really nice to have [Recaptcha](https://www.google.com/recaptcha/intro/index.html) support within this plugin. Let's discuss the feasibility of it?

**Comment by Bloke** [comment]
In the core plugin, probably not. But as a separate anti-spam module, sure why the heck not. If you like reCaptcha (I personally don't) then it's fairly simple to hook into either the `zemcontact.submit` or `zemcontact.deliver` callbacks to do checking and verification for any tools out there.

The module could even have its own output tag(s) if you wished, which could:

* drop your API key(s) into the form (or you can have an administrator put them manually into your `<form>`, like the MailChimp module requires).
* render the correct HTML with appropriate `data-` parameters.

It's just code :-p

**Comment by philwareham** [comment]
I've never liked recaptcha in the past, but "the latest version seems quite nice":http://googleonlinesecurity.blogspot.co.uk/2014/12/are-you-robot-introducing-no-captcha.html

**Comment by Bloke** [comment]
It does look better on the surface. Must be some serious stuff going on in the background to determine if such a simple click comes from a real input device/finger versus a javascript `click()` event fired by a bot.

I'm still not keen on the wording of the supplemental questions, assuming the sample images are indicative of the type of content they deliver: "Select all images that match this one". Well, being belligerent about it, none of them exactly match! But that's nitpicking on behalf of users who may or may not know why they're being asked random questions.

As an aside, in order to move to the next step in a form on a site the other week, I was presented with an image and four randomly-cut jigsaw pieces of the same image. My task was to drag and drop the pieces around the canvas to reconstruct the image. The interface was maddening and the bits had to exactly tessellate in order to "pass". And if you got it wrong, you were given a different image and had to start again. I gave up after one failed attempt and they didn't get my business.

**Comment by Bloke** [comment]
Won't be added to core ZCR. If anyone wants to make an add-on module, be my guest.
