### ISSUE TITLE
Radio buttons and checkboxes - value attribute option

### ISSUE THREAD

**Issue by philwareham** [Bloke/zem_contact_reborn#23]
There should be a way to specify `value` attribute for radios and checkbox inputs. We have this attribute for `select option` tags but not on radios and checkboxes.

**Comment by Bloke** [comment]
What benefit does it give for radios? When the email arrives it has the selected `label` name assigned to the value you gave for the `group`, e.g.:

...
Favourite colour: Green
...

The fact it uses hashes for the `value` attribute in the HTML are to prevent naming conflicts, and to ensure the selected radio ties up with the correct group upon submit. Think what would happen if you had multiple Yes / No radios on the page and gave the options the same value in each group. Which 'yes' was submitted?

Checkboxes, maybe. If the box is ticked, the email contains Yes against the chosen checkbox label. I haven't tried this by building my own `body_form` but assume that'll return Yes/No as well (testing appreciated). Maybe that's not enough and you should be able to specify what value is assigned in the email. This might become more important if checkbox sets are somehow permitted in the plugin.

If you have a specific use case where defining your own value helps for radios or checkboxes, then by all means drop it here and I'll see what can be done.

**Comment by philwareham** [comment]
I just think it should be optional extra, that an author could utilise if they want their own values for checkboxes and radios when they don't want the label simply regurgitated as the value.

For example, input:

    Are you potentially going to run, Logan?
    [ ] yes I will, because Jessica is hot and I'm nearly 30 myself
    [ ] maybe, what's it to you?
    [*] of course not, I'm happy to be vaporised when I turn 30

Example output:

    Will Logan run?
    No

**Comment by Bloke** [comment]
Makes sense. Not sure what'll happen if the values clash though. That might prevent this being useful (unless a check is made that no value has been used twice as the form is processed). Will have to see.

Consider this added to the list of things to investigate.

**Comment by philwareham** [comment]
Why would it matter if values clash? Values can be repeated within forms as many times as you like.

If an author repeats the value in the same *radio group* though, that's their fault.

**Comment by Bloke** [comment]
Actually, you're right. It stores stuff against the individual label so it won't matter about clashes, sorry for the mix-up,

For the record, the other field types don't actually have a `value` per se, they just use whatever has been given as the `name ` attribute as their value.

For the two anomaly field types, currently:

* Checkboxes see if the option has been ticked and store Yes if so, or No otherwise.
* Radios use the hash value generated by the plugin internally, and store the selected label.

I thought maybe it would be enough to output the `name` attribute verbatim in both these cases, if a name has been given for that tag, otherwise use the current values that the plugin employs. But it seems it uses the `name` as the key against which to store each field (which defaults to the label if no name is given). So in that case, if you had two Yes/No/Maybe radio sets and used the same names for each, the groups would overwrite one another upon submit.

I'm just trying to get away with not having to add a new `value` attribute, since it would only apply to the radio and checkbox. Maybe there's some internal wrangling I can use on the stored array so groups won't clash.

**Comment by philwareham** [comment]
Sorry Stef, I'm a little confused here

1. The other field types `value` is whatever the user types into that field, surely? You also have a `default` attribute on the textual input/textarea fields which allows for an initial `value` I believe.
2. You can't have two button groups sharing the same `name` in HTML. If radio buttons share the same name (no mater where in the form they are) they are all part of the same button group. That is intended functionality.

**Comment by Bloke** [comment]
I'm going to get in the bin.
